const AuthAction = {
  SAVE_USER_INFO: "AUTH_SAVE_USER_INFO",
  USER_LOGOUT: "AUTH_USER_LOGOUT",
  SAVE_USER_TOKEN: "AUTH_SAVE_USER_TOKEN",
  UPDATE_USER_PROFILE: "AUTH_UPDATE_USER_PROFILE"
}
export default AuthAction;